### ISSUE TITLE
missing webpack-sources in dependencies

### ISSUE THREAD

**Issue by bryanchen-d** [xz64/license-webpack-plugin#107]
`webpack-sources` is missing from the `dependencies` field of package.json. 
In most of the cases it won't block because webpack-sources would be installed by 'webpack', but somehow in my environment webpack install webpack-sources in its nested node_modules (most likely it is because I upgraded webpack). 

Also the dependency version of webpack-sources can be updated to webpack-sources^3.0.0, at least webpack-sources@1 doesn't work with webpack@5.53.0 and it will throw error `item.node is not a function`.

**Comment by epelc** [comment]
Please update this. The latest angular v13 production builds do not work without it.


```

[error] Error: Cannot find module 'webpack-sources'
Require stack:
- ~/myproject/node_modules/license-webpack-plugin/dist/WebpackAssetManager.js
- ~/myproject/node_modules/license-webpack-plugin/dist/LicenseWebpackPlugin.js
- ~/myproject/node_modules/license-webpack-plugin/dist/index.js
- ~/myproject/node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js
- ~/myproject/node_modules/@angular-devkit/build-angular/src/webpack/configs/index.js
- ~/myproject/node_modules/@angular-devkit/build-angular/src/builders/browser/index.js
- ~/myproject/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- ~/myproject/node_modules/@angular-devkit/architect/node/index.js
- ~/myproject/node_modules/@angular/cli/models/architect-command.js
- ~/myproject/node_modules/@angular/cli/commands/build-impl.js
- ~/myproject/node_modules/@angular-devkit/schematics/tools/export-ref.js
- ~/myproject/node_modules/@angular-devkit/schematics/tools/index.js
- ~/myproject/node_modules/@angular/cli/utilities/json-schema.js
- ~/myproject/node_modules/@angular/cli/models/command-runner.js
- ~/myproject/node_modules/@angular/cli/lib/cli/index.js
- /Users/ed/.nvm/versions/node/v16.13.0/lib/node_modules/@angular/cli/lib/init.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (~/myproject/node_modules/license-webpack-plugin/dist/WebpackAssetManager.js:4:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (~/myproject/node_modules/license-webpack-plugin/dist/LicenseWebpackPlugin.js:12:29)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

```

^ for google by other people looking for this issue

**Comment by xz64** [comment]
@bryanchen-d @epelc Can you please try in v4.0.0? I haze include webpack-sources@^3.0.0 as a direct dependency now.

**Comment by epelc** [comment]
Thanks @xz64 I can confirm 4.0.0 works

```
npm i --save-dev license-webpack-plugin@4

# Fixes angular production build
ng build --configuration production
```

I'll raise an issue with @angular-devkit/build-angular to upgrade the dependency.

```
> npm ls license-webpack-plugin
└─┬ @angular-devkit/build-angular@13.0.2
  └── license-webpack-plugin@3.0.0
```
